"""
CRUD stands for Create, Read, Update, and Delete.
This file contains all the helper functions that actually perform these actions on the database.
Think of it as the "instruction manual" for interacting with the database.
When a router receives a request (e.g., "Give me all products"), it calls a function in this file to do the heavy lifting.
"""

# 1. Importing necessary components
# ---------------------------------------------------------
# 'Session' is the database connection object. We need it to run queries.
from sqlalchemy.orm import Session

# 'IntegrityError' is a specific error that happens when we violate a database rule.
# For example, if we try to create a user with an email that already exists, 
# and the database was told emails must be unique, it throws this error.
from sqlalchemy.exc import IntegrityError

# 'HTTPException' is used to send standard web errors back to the frontend.
# E.g., Error 404 (Not Found) or 400 (Bad Request).
from fastapi import HTTPException

# We import our own models (database tables) and schemas (data structures).
from . import models, schemas


# ==========================================
# PRODUCT CRUD OPERATIONS
# ==========================================

def get_product(db: Session, product_id: int):
    """
    Reads a single product from the database using its ID.
    It asks the database: "Query the Product table, filter by ID, and give me the first match."
    """
    return db.query(models.Product).filter(models.Product.id == product_id).first()

def get_product_by_sku(db: Session, sku: str):
    """
    Reads a single product using its unique SKU (Stock Keeping Unit).
    """
    return db.query(models.Product).filter(models.Product.sku == sku).first()

def get_products(db: Session, skip: int = 0, limit: int = 100):
    """
    Reads a list of products.
    'skip' and 'limit' are used for pagination. 
    E.g., if skip=10 and limit=10, it gives us products 11 through 20.
    """
    return db.query(models.Product).offset(skip).limit(limit).all()

def create_product(db: Session, product: schemas.ProductCreate):
    """
    Takes data from the user (schemas.ProductCreate), converts it into a database row (models.Product),
    and saves it to the database.
    """
    # 1. Convert the Pydantic schema into a dictionary, then spread it into the SQLAlchemy model.
    db_product = models.Product(**product.model_dump())
    
    # 2. Add the new row to the database session.
    db.add(db_product)
    
    try:
        # 3. Commit (save) the changes permanently.
        db.commit()
        
        # 4. Refresh updates our Python object with any new data generated by the database (like the auto-generated ID).
        db.refresh(db_product)
        return db_product
    except IntegrityError:
        # If the SKU already exists, SQLAlchemy throws an IntegrityError.
        # We roll back the transaction so the database doesn't get stuck in an error state.
        db.rollback()
        # We tell the frontend: 400 Bad Request - SKU already exists.
        raise HTTPException(status_code=400, detail="SKU already exists")

def update_product(db: Session, product_id: int, product: schemas.ProductUpdate):
    """
    Finds an existing product and changes its details.
    """
    # 1. Get the current product from the database.
    db_product = get_product(db, product_id)
    if not db_product:
        # If it doesn't exist, return None (the router will handle sending a 404 error).
        return None
        
    # 2. Get the new data provided by the user. 
    # 'exclude_unset=True' means we only update fields the user ACTUALLY sent. 
    # If they didn't send a new price, we don't touch the price.
    update_data = product.model_dump(exclude_unset=True)
    
    # 3. Loop through the provided data and update the database object.
    for key, value in update_data.items():
        setattr(db_product, key, value)
        
    try:
        # 4. Save the changes
        db.commit()
        db.refresh(db_product)
        return db_product
    except IntegrityError:
        db.rollback()
        raise HTTPException(status_code=400, detail="SKU already exists")

def delete_product(db: Session, product_id: int):
    """
    Finds a product and removes it from the database.
    """
    db_product = get_product(db, product_id)
    if db_product:
        db.delete(db_product)
        db.commit()
    return db_product


# ==========================================
# CUSTOMER CRUD OPERATIONS
# ==========================================
# (These follow the exact same logic as the Product CRUD operations above)

def get_customer(db: Session, customer_id: int):
    return db.query(models.Customer).filter(models.Customer.id == customer_id).first()

def get_customer_by_email(db: Session, email: str):
    return db.query(models.Customer).filter(models.Customer.email == email).first()

def get_customers(db: Session, skip: int = 0, limit: int = 100):
    return db.query(models.Customer).offset(skip).limit(limit).all()

def create_customer(db: Session, customer: schemas.CustomerCreate):
    db_customer = models.Customer(**customer.model_dump())
    db.add(db_customer)
    try:
        db.commit()
        db.refresh(db_customer)
        return db_customer
    except IntegrityError:
        # Here, the IntegrityError would happen if the email already exists
        db.rollback()
        raise HTTPException(status_code=400, detail="Email already exists")

def delete_customer(db: Session, customer_id: int):
    db_customer = get_customer(db, customer_id)
    if db_customer:
        db.delete(db_customer)
        db.commit()
    return db_customer


# ==========================================
# ORDER CRUD OPERATIONS
# ==========================================

def get_order(db: Session, order_id: int):
    return db.query(models.Order).filter(models.Order.id == order_id).first()

def get_orders(db: Session, skip: int = 0, limit: int = 100):
    return db.query(models.Order).offset(skip).limit(limit).all()

def create_order(db: Session, order: schemas.OrderCreate):
    """
    Creating an order is complex because it affects multiple tables: 
    It creates an Order, creates OrderItems, AND reduces Product stock.
    """
    
    # 1. Ensure the customer who is placing the order actually exists.
    db_customer = get_customer(db, order.customer_id)
    if not db_customer:
        raise HTTPException(status_code=404, detail="Customer not found")

    # Variables to keep track of the total price and the items being ordered.
    total_amount = 0.0
    order_items = []
    
    # 2. Loop through every item the user is trying to buy.
    for item in order.items:
        # Check if the product exists
        db_product = get_product(db, item.product_id)
        if not db_product:
            raise HTTPException(status_code=404, detail=f"Product with id {item.product_id} not found")
        
        # IMPORTANT: Check if we have enough stock to fulfill this item.
        if db_product.stock_quantity < item.quantity:
            raise HTTPException(status_code=400, detail=f"Insufficient stock for product '{db_product.name}'")
        
        # Deduct the ordered quantity from our inventory stock.
        db_product.stock_quantity -= item.quantity
        
        # Add the cost of these items to the total bill.
        total_amount += db_product.price * item.quantity
        
        # Create an OrderItem database record (but we haven't saved it yet).
        order_items.append(
            models.OrderItem(product_id=item.product_id, quantity=item.quantity)
        )
    
    # 3. Create the main Order record with the calculated total amount and items.
    db_order = models.Order(
        customer_id=order.customer_id,
        total_amount=total_amount,
        items=order_items
    )
    
    # 4. Save everything to the database.
    # Note: Because of how SQLAlchemy works, adding the `db_order` automatically adds the `order_items` too.
    # Also, because we haven't committed yet, if ANYTHING failed above (like out of stock), 
    # NO changes are saved to the database. It's an all-or-nothing transaction.
    db.add(db_order)
    db.commit()
    db.refresh(db_order)
    
    return db_order

def delete_order(db: Session, order_id: int):
    """
    Deletes an order.
    Because we set `cascade="all, delete-orphan"` in models.py, 
    deleting an order will automatically delete all the associated OrderItems too!
    """
    db_order = get_order(db, order_id)
    if db_order:
        db.delete(db_order)
        db.commit()
    return db_order
